/******************************************************************************/
/****         Generated by IBExpert 2008.08.08 30/05/2015 19:02:11         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE '127.0.0.1:C:\ControledePedidos\BASESISTEMA.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_CLIENTES_ID;
SET GENERATOR GEN_CLIENTES_ID TO 15;

CREATE GENERATOR GEN_ENDERECOS_ID;
SET GENERATOR GEN_ENDERECOS_ID TO 0;

CREATE GENERATOR GEN_FORNECEDORES_ID;
SET GENERATOR GEN_FORNECEDORES_ID TO 4;

CREATE GENERATOR GEN_PEDIDOS_ID;
SET GENERATOR GEN_PEDIDOS_ID TO 12;

CREATE GENERATOR GEN_PEDIDOS_PRODUTO_ID;
SET GENERATOR GEN_PEDIDOS_PRODUTO_ID TO 24;

CREATE GENERATOR GEN_PRODUTOS_ID;
SET GENERATOR GEN_PRODUTOS_ID TO 16;

CREATE GENERATOR GEN_PRODUTOS_ID1;
SET GENERATOR GEN_PRODUTOS_ID1 TO 0;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE CLIENTES (
    CODIGO    INTEGER NOT NULL,
    NOME      VARCHAR(255),
    ENDERECO  VARCHAR(255),
    BAIRRO    VARCHAR(60),
    CIDADE    VARCHAR(60),
    UF        VARCHAR(2),
    CEP       VARCHAR(10),
    TELEFONE  VARCHAR(20)
);

CREATE TABLE ENDERECOS (
    ENDERECO        VARCHAR(255),
    BAIRRO          VARCHAR(60),
    CIDADE          VARCHAR(60),
    UF              VARCHAR(2),
    CEP             VARCHAR(10),
    CODIGO_CLIENTE  SMALLINT,
    CODIGO          INTEGER NOT NULL
);

CREATE TABLE FORNECEDORES (
    CODIGO    INTEGER NOT NULL,
    NOME      VARCHAR(255),
    ENDERECO  VARCHAR(255),
    BAIRRO    VARCHAR(60),
    CIDADE    VARCHAR(60),
    UF        VARCHAR(2),
    CEP       VARCHAR(10),
    TELEFONE  VARCHAR(20)
);

CREATE TABLE PEDIDOS (
    CODIGO           INTEGER NOT NULL,
    CLIENTES_CODIGO  INTEGER NOT NULL,
    DATA_PEDIDO      DATE,
    VALOR_TOTAL      FLOAT,
    DESCONTO         FLOAT
);

CREATE TABLE PEDIDOS_PRODUTOS (
    CODIGO          INTEGER NOT NULL,
    CODIGO_PRODUTO  INTEGER,
    CODIGO_PEDIDO   INTEGER,
    QUANTIDADE      INTEGER
);

CREATE TABLE PRODUTOS (
    CODIGO               INTEGER NOT NULL,
    FORNECEDORES_CODIGO  INTEGER NOT NULL,
    NOME                 VARCHAR(255),
    VALOR                DOUBLE PRECISION,
    ESTOQUE              INTEGER
);

INSERT INTO CLIENTES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, UF, CEP, TELEFONE) VALUES (15, 'LEONARDO PESSOA', 'RUA NOVA', 'CENTRO', 'CATOLE DO ROCHA', 'PB', '58884000', '8333444');

COMMIT WORK;

INSERT INTO FORNECEDORES (CODIGO, NOME, ENDERECO, BAIRRO, CIDADE, UF, CEP, TELEFONE) VALUES (1, 'daruma automacao', 'Rua: Redentor,  344', 'Centro', 'guarulhos', 'SP', '5555555', '333333333');

COMMIT WORK;

INSERT INTO PRODUTOS (CODIGO, FORNECEDORES_CODIGO, NOME, VALOR, ESTOQUE) VALUES (16, 1, 'COCA COLA', 3, 1);

COMMIT WORK;



/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (CODIGO);
ALTER TABLE ENDERECOS ADD PRIMARY KEY (CODIGO);
ALTER TABLE FORNECEDORES ADD CONSTRAINT PK_FORNECEDORES PRIMARY KEY (CODIGO);
ALTER TABLE PRODUTOS ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY (CODIGO);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_1 FOREIGN KEY (FORNECEDORES_CODIGO) REFERENCES FORNECEDORES (CODIGO);


/******************************************************************************/
/****                               Indices                                ****/
/******************************************************************************/

CREATE INDEX ENDERECOS_IDX2 ON ENDERECOS (CODIGO_CLIENTE);
CREATE UNIQUE INDEX PK_PEDIDOS ON PEDIDOS (CODIGO);
CREATE UNIQUE INDEX PK_PEDIDOS_PRODUTOS ON PEDIDOS_PRODUTOS (CODIGO);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: CLIENTES_BI */
CREATE TRIGGER CLIENTES_BI FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.codigo is null) then
    new.codigo = gen_id(gen_clientes_id,1);
end
^

/* Trigger: FORNECEDORES_BI */
CREATE TRIGGER FORNECEDORES_BI FOR FORNECEDORES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.codigo is null) then
    new.codigo = gen_id(gen_fornecedores_id,1);
end
^

/* Trigger: PEDIDOS_BI */
CREATE TRIGGER PEDIDOS_BI FOR PEDIDOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.codigo is null) then
    new.codigo = gen_id(gen_pedidos_id,1);
end
^

/* Trigger: PEDIDOS_PRODUTOS_BI */
CREATE TRIGGER PEDIDOS_PRODUTOS_BI FOR PEDIDOS_PRODUTOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.codigo is null) then
    new.codigo = gen_id(gen_pedidos_produto_id,1);
end
^

/* Trigger: PRODUTOS_BI */
CREATE TRIGGER PRODUTOS_BI FOR PRODUTOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.codigo is null) then
    new.codigo = gen_id(gen_produtos_id,1);
end
^

SET TERM ; ^

